version: '3.8'
services:
  marker-service:
    build: .
    ports:
      - "8001:8000"
    environment:
      - TORCH_DEVICE=cpu
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped